### ISSUE TITLE
Doesnt request permission on iPhone 5S

### ISSUE THREAD

**Issue by ArseniyBorezkiy** [pbakondy/cordova-plugin-speechrecognition#10]
Never calls callbacks in requestPermission. No output in console. iOS.
It is NOT depended of 
  'NSMicrophoneUsageDescription permission'
  'NSSpeechRecognitionUsageDescription permission'
in my .plist file.

window.plugins.speechRecognition.requestPermission(function () {
// never
}, function () { // never })

**Comment by pbakondy** [comment]
What is the version of the operating system?

**Comment by ArseniyBorezkiy** [comment]
9.2.1 - function available => hasPermission => No => requestPermission =>
silence...

It is normal?

2016-12-20 14:00 GMT+05:00 Peter Bakondy <notifications@github.com>:

**Comment by pbakondy** [comment]
iOS 10 is required.

See README:
https://github.com/pbakondy/cordova-plugin-speechrecognition#requirements-1

**Comment by ArseniyBorezkiy** [comment]
Thanks, but It is strange that isRecognitionAvailable returns true.

2016-12-20 14:42 GMT+05:00 Peter Bakondy <notifications@github.com>:

**Comment by ArseniyBorezkiy** [comment]
Please, tell me, is there correct ways (pay-free) to use speech recognition
in cordova in  <10 iOS ? Thanks.

2016-12-20 14:45 GMT+05:00 Арсений Борецкий <apborezkiy@gmail.com>:

**Comment by pbakondy** [comment]
There are 3rd party solutions.
I never used them before.
