### ISSUE TITLE
Not working on iOS 13.2

### ISSUE THREAD

**Issue by jjorae** [pbakondy/cordova-plugin-speechrecognition#105]
Hi,
I using this plugin in ionic3.
It worked fine when deployed prior to iOS 13.2, but an error occurred in iOS 13.2.
Has anyone encountered this same problem?

**Comment by markenapps** [comment]
Yes. My users are reporting this issue with iOS 13.2 too. I'm not able to provide error details yet. Sounds like speechRecognition.stopListening() is not working probably.

**Comment by desmeit** [comment]
same problem here.

**Comment by Jayasimhapatel** [comment]
Yes we are facing same issue in ios 13.2.2 but works fine till ios 12.

**Comment by Jayasimhapatel** [comment]
We are unable to proceed to use this plugin in ios 13.2.2 . It fails with error message "Error Domain=kAFAssistantErrorDomain Code=209 "Null"" 
Please suggest any fix.

**Comment by desmeit** [comment]
I think IOS 13.3 should fix it:

https://forums.developer.apple.com/thread/125279

**Comment by Durzan666** [comment]
I think it is not a new issue. See https://github.com/pbakondy/cordova-plugin-speechrecognition/issues/13

**Comment by jjorae** [comment]
> I think it is not a new issue. See #13

I think it's a different issue. I can't get the result no matter how many times I try. And this is an issue with iOS 13.2.2, not with iOS 10 or earlier.

**Comment by jjorae** [comment]
I updated to iOS 13.2.3 version today. No more issues.

**Comment by markenapps** [comment]
Ok. May be you have to wait until 13.3. Hava a look at:
https://forums.developer.apple.com/thread/125279

Greetings
Markus Liebschner

Am Mi., 20. Nov. 2019 um 02:25 Uhr schrieb Raehyeok, Cho <
notifications@github.com>:
