### ISSUE TITLE
Error on No speech.

### ISSUE THREAD

**Issue by Truedison** [pbakondy/cordova-plugin-speechrecognition#11]
When i run startlistening, and stopping it without recording/speaking it produces error. Is this a correct behaviour ?

**Comment by pbakondy** [comment]
Yes it is. You expect recognized terms when you start the recognition process. When the recognition is unsuccessful ( because of any reason like not speaking/network error/noisy environment/etc ) it can't return with success callback.

BTW what error message do you get?

**Comment by Truedison** [comment]
Here it is 

"Error Domain=kAFAssistantErrorDomain Code=203 \"Retry\" UserInfo={NSLocalizedDescription=Retry, NSUnderlyingError=0x170254760 {Error Domain=SiriSpeechErrorDomain Code=1 \"(null)\"}}"

I was able to reproduce this error by stopping it  without even talking. I was having a hard time getting the error since its not in json. Thanks for the response

**Comment by pbakondy** [comment]
Yeah, Apple should improve the documentation. I could not find any usable list of kAFAssistantErrorDomain error codes anywhere.

**Comment by Truedison** [comment]
Okay thanks for the response, Maybe ill land this on a general error. Thanks !

**Comment by Truedison** [comment]
Ill just close this issue thnaks

**Comment by Ahmadbaba46** [comment]
Does it require network to work?
 It always return error to me even if i talk.

**Comment by Truedison** [comment]
@Ahmadbaba46 Yep

**Comment by Ahmadbaba46** [comment]
@Truedison thanks, it works

**Comment by Truedison** [comment]
@Ahmadbaba46 no problem same behaviour with siri no internet = sad
