### ISSUE TITLE
Problem with Samsung SM-T235 tablet

### ISSUE THREAD

**Issue by gecsafunk** [pbakondy/cordova-plugin-speechrecognition#14]
First of all: big thanks for this plugin!
I have implemented this plugin successfully in my hybrid app project..It is working well on my iphone 6 and xiaomi redmi smartphones.
I have problem if i want to run my app on the Samsung SM-T235 tablet (Android version 5.1.1) ..I don't receive any error message, just the whole Phonegap library is not working. Without this plugin everything is fine.
I use the Phonegap Build Service (cli-6.5.0).
Any suggestions would be appreciated!

**Comment by pbakondy** [comment]
It's hard to tell anything without any error message or logs.
Try creating a simple cordova project with this plugin only and run it on your device.

**Comment by gecsafunk** [comment]
Thanks for the reply...that's a good idea..i made a minimalist project. This plugin kill the Phonegap interface on the Samsung SM-T235 without any error message. This simple app still working on the iPhone 6...and probably on the Xiaomi Redmi. It is interesting that the Android 6 devices does not any problem with it. Do You have experiences from the usage of the Android 5 devices?

**Comment by pbakondy** [comment]
No, I tested it only with a Android 6 device.
Maybe you could check logcat logs if you see any exception. 
It requires Android SDK and a wired connection to your computer.

**Comment by gecsafunk** [comment]
Thanks for the information! 
I tried the application on an other Samsung SM-T235 machine meanwhile. It worked perfectly! After this situation I made hard reset on the original device. All the two machines same type, with the same operating system (5.1.1) the original can't run the plugin, the other run it perfectly!
Peter, thanks for your help, I think that this issue is just a specific problem.
