### ISSUE TITLE
startListening don't work on iOS 10

### ISSUE THREAD

**Issue by LUCIANOSOLER** [pbakondy/cordova-plugin-speechrecognition#17]
I implemented functions in this order and works ok on Android, but startListening doesn't works on iOS 10.

Functions
Avaliable - (works on android and iOS)
HasPermition - (works on android and iOS)
RequestPermition -  (works on android and iOS)

But startListening -  (works on android, but not works on iOS 10)

I already given permission  on NSMicrophoneUsageDescription and
NSSpeechRecognitionUsageDescription with its string value in info.plist

I call permissions before i call startListening, but doesn´t works on iOS.

I am with:
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002

The erros that appears to me is --> error domain=kAFAssistantErrorDomain, same as others issues.

Can you have some idea why this is happen?

**Comment by pbakondy** [comment]
sadly Apple provides poor support for Speech API. Just look at the official forum:
https://forums.developer.apple.com/search.jspa?q=kAFAssistantErrorDomain

I really not able to tell you what could be the problem. It works on my device and I can not reproduce this error.

**Comment by LUCIANOSOLER** [comment]
I understand, can you send me your project?
maybe some configuration of your project can be different and work here.

**Comment by aurothic** [comment]
I'm also receiving `Error Domain=kAFAssistantErrorDomain Code=1 "(null)" `. In some circumstances recognition works, but only after idling for several minutes. More in [this](http://prntscr.com/ea2nfx) picture.

**Comment by aurothic** [comment]
I should mention the above also works flawlessly on Android.

**Comment by mosca90** [comment]
Same error here, with this plugin and with https://github.com/macdonst/SpeechRecognitionPlugin
tested on iOS 10 and both do not work.
On android, no problem.

**Comment by mosca90** [comment]
Here more infos: https://github.com/macdonst/SpeechRecognitionPlugin/issues/88#issuecomment-281378459

**Comment by pbakondy** [comment]
Please check last release

**Comment by aurothic** [comment]
How can we update from Ionic?

**Comment by aurothic** [comment]
I am still experiencing issues with using the code that I provided above. Here are the steps I took:

1. Update ionic-native
2. Make a button that is bound to the function voiceSearch that is listed in a previous comment.
3. Tap button and say "What is the time". 
     a. Wait.
     b. No response. Nothing logged in console.
4. Tap button and say "What is the time".
     a. Wait
     b. Error logged in the console.
5. Tap button and say "What is the time".
     a. Wait
     b. Returns identified words in the console.

Can you please provide a function similar to mine that works on both ios and android? Currently the function voiceSearch that I listed above works fine on android. If it's impossible to write a function that works for both platforms, can you provide a snippet that works for ios only? 

Thank you!

**Comment by mosca90** [comment]
@aurothic, How long did you wait?
Seems that needs to wait for about 1 minute for a response back, can you try?

**Comment by pbakondy** [comment]
@aurothic you don't need to update ionic-native package.
You have to update the cordova plugin itself.

```
cordova plugin rm cordova-plugin-speechrecognition
cordova plugin add cordova-plugin-speechrecognition
```

**Comment by LUCIANOSOLER** [comment]
Thanks @pbakondy now works ...

**Comment by pbakondy** [comment]
Great!
Can we close the issue?

**Comment by aurothic** [comment]
This worked for me as well. However, there still is the matter of waiting for a 1 minute timeout before displaying the results. Android detects when the user stops talking, is there any such way to do this on IOS?

**Comment by LUCIANOSOLER** [comment]
For ios use stopListening method.

**Comment by aurothic** [comment]
Yes, but when should I call it? Currently I have a button that starts the listening process. This works very well on android, does it not carry over to ios?

**Comment by LUCIANOSOLER** [comment]
You need use plugin "Platform" to knows if you are on android or ios.
https://ionicframework.com/docs/v2/api/platform/Platform/

On my app I put timer when i call startListening for ios ( 5 seconds ) when time over, the program calls stopListening

**Comment by aurothic** [comment]
Seems like bad practice. Perhaps this plugin could be used with [DB Meter](http://ionicframework.com/docs/v2/native/db-meter/).

**Comment by Ezhilarasan14** [comment]
**Error: exec proxy not found for :: SpeechRecognition :: isRecognitionAvailable**


console.log(window.plugins.speechRecognition);
this line is working fine

{
getSupportedLanguages: ƒ (successCallback, errorCallback)
hasPermission: ƒ (successCallback, errorCallback)
isRecognitionAvailable: ƒ (successCallback, errorCallback)
requestPermission: ƒ (successCallback, errorCallback)
startListening: ƒ (successCallback, errorCallback, options)
stopListening: ƒ (successCallback, errorCallback)
}

function startRecordingSpeech(){
    console.log(window.plugins.speechRecognition);
    window.plugins.speechRecognition.isRecognitionAvailable(successCallback,errorCallback);

}
function successCallback(){
    console.log(callBackResult);
}
function errorCallback(callBackResult){
    console.log(callBackResult);
//**Error: exec proxy not found for :: SpeechRecognition :: isRecognitionAvailable**
}

**Comment by atul-athawale** [comment]
With Ionic 4 not working on IOS.
Getting below error.
TypeError: Object(__WEBPACK_IMPORTED_MODULE_1__ionic_native_core__["cordova"]) is not a function. (In 'Object(__WEBPACK_IMPORTED_MODULE_1__ionic_native_core__["cordova"])(this, "isRecognitionAvailable", {}, arguments)', 'Object(__WEBPACK_IMPORTED_MODULE_1__ionic_native_core__["cordova"])' is an instance of Object)
