### ISSUE TITLE
IOS App freezes at finished loading the index page after installation of the plugin

### ISSUE THREAD

**Issue by lawrencechahld** [pbakondy/cordova-plugin-speechrecognition#19]
My app can run normally before. However the app froze at at finished loading of index page after installation of the plugin. Permission granted.

I didn't change any coding and have not yet initialized nor called the plugin, no error message in console. 

Angular project 
cordova version 6.4.0
cordova platform version - ios 3.9.1 
ios 10.2.1

**Comment by pbakondy** [comment]
This is not enough information.
Try first to create a new cordova project with this plugin only.

**Comment by lawrencechahld** [comment]
As your suggested solution, problem resolved. 
Thank your for your plugin.
