### ISSUE TITLE
Android 7.1.1 does start listening

### ISSUE THREAD

**Issue by r4nm4** [pbakondy/cordova-plugin-speechrecognition#24]
Hi,
I have the same issue mentioned in Android 7.0 with my Android 7.1.1.
Everything works amazing in all iOS versions and Android 5.x and 6.x

In Android 7.1.1 my catlog is:

03-23 16:42:47.584  1612  1649 D SpeechRecognition: execute() action hasPermission
03-23 16:42:47.589  1612  1649 D SpeechRecognition: execute() action requestPermission
03-23 16:42:47.592  1612  1649 D SpeechRecognition: execute() action startListening
03-23 16:42:47.594  1612  1649 D SpeechRecognition: startListening() language: en-US, matches: 1, prompt: Hi, showPopup: false

I have tried with "prompt" null or with string and with "showPopup" true and false.
Nothing changed.

Any idea? Thank you so much for your plugin.
Regards

**Comment by pbakondy** [comment]
Please complete the case.
What method did you call with parameters.
What is happening? What is the expected behavior?

**Comment by r4nm4** [comment]
Thank you for your answer.
I'm sorry, I'm confuse about your request because I thought to sent you all informations that you requested inside the catlog.

A: What method did you call with parameters?
Q: As a catlog, I called "startListening()" with params:
"language": "en-US", "matches": "1", "prompt": "Hi", "showPopup": false

A: What is happening?
Q: Nothing happen... and nothing inside the catlog too

A: What is the expected behavior?
Q: I'm expecting to receive the successCallback from "startListening()" method.

I hope this can help you, otherwise my apologies because I didn't understand what you need :)
Thank you again

Regards

**Comment by pbakondy** [comment]
Chris, could you show me the JS code as well? Based on the catlog I think
you call  three methods of this plugin consecutively.
Does the startListening call the error callback?

**Comment by r4nm4** [comment]
Thank you fro your help! :)

This is my simple code:

var speechRecognitionPlugin = window.plugins.speechRecognition;
if (!speechRecognitionPlugin.hasPermission()) {
    speechRecognitionPlugin.requestPermission();
}
speechRecognitionPlugin.startListening(function onListening(data) {
	if (data) {
		// process data result
	} else {
		// error
	}
}, function onErrorListening(data) {
	// error
}, {
	language: "en-US", 	matches: 1, prompt: "", showPopup: false,	showPartial: false
});

**Comment by r4nm4** [comment]
Update:
Maybe is a device error, I have debug all catlog stuff and I think is not a plugin issue.
I will update you Monday when I will test the app with more Android 7.1 devices.
Thank you for your help :)

**Comment by pbakondy** [comment]
This JS code is not right. You should use callbacks everywhere.
You should not call startListening right after requestPermission, these are asynchronous processes. 
Function startListening() returns with error callback but you don't print out the results.

**Comment by r4nm4** [comment]
I see what you mean about the requestPermission() and I did that in another test.
requestPermission callback is just "OK".

About the startListening() callback, I'm using that (in my example is onErrorListening()) but I don't receive anything from data.

This is another example:
var speechRecognitionPlugin = window.plugins.speechRecognition;
speechRecognitionPlugin.requestPermission(function (res){
console.log(res); // res = OK
speechRecognitionPlugin.startListening(function onListening(data) {
if (data) {
// process data result
} else {
// error
}
}, function onErrorListening(data) {
// error
console.log(data);
}, {
language: "en-US", matches: 1, prompt: "", showPopup: false, showPartial: false
});
});

I can continue all my test on Monday.
Thank you for your help, I really appreciate that.
But still, I think is not a plugin issue :)

**Comment by r4nm4** [comment]
Hi,
I'm sorry, but was not a plugin issue.
My apologies.
Apparently I fixed the issue after enter inside the google app and allow the mic permission.
The method "hasPermission" always callback with true.
For sure the issue was from google device api.

Thank you for your help and your time.
Regards
