### ISSUE TITLE
startListening() not sure why it is not working

### ISSUE THREAD

**Issue by PiotrMa** [pbakondy/cordova-plugin-speechrecognition#35]
Hi 
I have some problem with startListening() - it doesnt work.
My code:
`window.plugins.speechRecognition.isRecognitionAvailable(
        function(){
            
            window.plugins.speechRecognition.hasPermission(
                function(){
                    alert("hello")
                    
                    /*window.plugins.speechRecognition.startListening(
                        function(){
                            alert("recorded");
                        }, 
                        function(errorMsg){
                            alert(errorMsg);
                        }, 
                        {
                          String language = window.navigator.language,
                          Number matches = 1,
                          String prompt = "",      // Android only
                          Boolean showPopup = false,  // Android only
                        });*/
                }, 
                function(){alert("App doesn't have permissions granted.");});

        },
        function(){alert("Somethign went wrong.");}
    );`

RIght now "hello" alert pops up before the recording" page is loaded - my first cordova project,
and if I uncomment startListening() the popup doesnt show up at all and nothing happens.

This code should run after pushing a button in "home_page" but after loading "add_page". Am i also not sure if Function successCallback should be function(result){ //result = array ?}. I would really apprecieate help or working example.

Thanks

**Comment by pbakondy** [comment]
the js code is not valid. use a js validator like eslint

**Comment by Ahmadbaba46** [comment]
Here is the error
{
                      String language = window.navigator.language,
                      Number matches = 1,
                      String prompt = "",      // Android only
                      Boolean showPopup = false,  // Android only
                    }

It should be this

{
                      language: window.navigator.language,
                      matches : 1,
                      prompt : "",      // Android only
                      showPopup : false,  // Android only
                    }

**Comment by PiotrMa** [comment]
Wow, that was foolish of me. Thanks! But still despite hasPermission returns ok when running startListening() it throws errorCode = "missing perminnions". My permissions in manifext file:
`<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
