### ISSUE TITLE
Disable "beep" sound on start and stop

### ISSUE THREAD

**Issue by yasseralsamman** [pbakondy/cordova-plugin-speechrecognition#39]
Hi
is there any way to disable the beep sound on starting and stopping ? 
I'm using Ionic 2 and building for Android.

I tried Media Plugin but it does not seem to be able to affect system sounds. 

Thanks in advance.

**Comment by ragcsalo** [comment]
You should mute the Multimedia (music) stream.
Edit "SpeechRecognition.java" and add this to the startListening method to line 157 (before initiating the recognition):

AudioManager audioManager = (AudioManager) context.getSystemService(Context.AUDIO_SERVICE);
audioManager.adjustStreamVolume(AudioManager.STREAM_MUSIC, AudioManager.ADJUST_MUTE, 0);

**Comment by mano42023** [comment]
@ragcsalo  Hi I did this but still getting beep sound.. :(

**Comment by JackJohnG** [comment]
this one works for me
AudioManager audioManager=(AudioManager)context.getSystemService(Context.AUDIO_SERVICE);
audioManager.setStreamVolume(AudioManager.STREAM_MUSIC, 0, AudioManager.FLAG_REMOVE_SOUND_AND_VIBRATE);

I advise first to get the current volume using:
audioManager.getStreamVolume(AudioManager.STREAM_MUSIC);

then set volume to 0 and after you are done with recording you can reset volume to the initial one

**Comment by eServantQuid** [comment]
Hi @JackJohnG , can you please provide a full working example? Where i have to put the reset volume to the initial one?

Thanks

**Comment by texano00** [comment]
Hi @JackJohnG , can you please provide a full working example? Where i have to put the reset volume to the initial one?

Thanks

**Comment by ragcsalo** [comment]
I mute the media volume in the onCreate function of my MainActivity, and restore the volume in the onDestroy function. I had to create the variable first (which stores the original volume level). My code is:

```
private Integer original_volume_level;
private AudioManager audioManager = (AudioManager) getSystemService(Context.AUDIO_SERVICE);

onCreate:
=========
original_volume_level = audioManager.getStreamVolume(AudioManager.STREAM_MUSIC);
audioManager.adjustStreamVolume(AudioManager.STREAM_MUSIC, AudioManager.ADJUST_MUTE, 0);
Toast.makeText(this, "Media volume muted.", Toast.LENGTH_SHORT).show();

onDestroy:
==========
audioManager.setStreamVolume(AudioManager.STREAM_MUSIC, original_volume_level, 0);
Toast.makeText(this, "Media volume restored.", Toast.LENGTH_SHORT).show();

```
I hope this helps. :-)

**Comment by JackJohnG** [comment]
@texano00 I created a very small [cordova plugin](https://github.com/JackJohnG/cordova-plugin-volumecontrol) to control volume in android
you can just download it as zip, unzip it into the folder of your project and then add it using command
*ionic cordova plugin add ./cordova-plugin-volumecontrol*

Then you can use it in any place of the application like this:
*window.VolumeControl.setVolume(0);*

So, you just need to call the above method just before you start speech recognition and after you are done you can call:
*window.VolumeControl.resetVolume();*

In case you need to change some behaviour inside plugin, you can simply edit VolumeControl.java file inside plugin but then do not forget to remove old version of plugin and add the new one.

If you have any questions you can write me an email

**Comment by yasseralsamman** [comment]
@JackJohnG  Nice one! I tried it and setVolume is working. resetVolume doesn't seem to be working though.
