### ISSUE TITLE
Request: Add DB Meter

### ISSUE THREAD

**Issue by r4nm4** [pbakondy/cordova-plugin-speechrecognition#41]
First of all, thank you for your hard work.
I'm wondering if is it possible to implement a DB meter inside this plugin.
I found a different cordova plugin that do exactly that
"https://github.com/akofman/cordova-plugin-dbmeter"
but seems that I can not use both.

I'm trying to "merge" both code just in 1 plugin... but maybe is something that someone else is also interested.
What do you think?

Thank you again.
Cheers

**Comment by pbakondy** [comment]
Nice idea.
On which platform did you try it?

**Comment by r4nm4** [comment]
Thanks!
I'm not a Java/iOS dev... but tomorrow I will try with Android first :)
In case I need, could I ask you your help? :)

**Comment by r4nm4** [comment]
I have tried for few hours in Android... but without success.
I continue to receive "ERROR_NETWORK" error
when I call "this.audioRecord.startRecording();"
Fail :(

**Comment by r4nm4** [comment]
Epic Fail!!!
My attention was on the wrong direction!!!
If you want to handle and display the dbMeter, just handle the value inside:
public void onRmsChanged(float rmsdB)
That's it.
Enjoy and happy coding!
