### ISSUE TITLE
Speech/Speech.h file not found

### ISSUE THREAD

**Issue by Xiralv** [pbakondy/cordova-plugin-speechrecognition#43]
Hello im getting an error in ios when i build it. the error is **Speech/Speech.h file not found** where can I find the speech.h? or the file of speech/speech.h?

**Comment by pbakondy** [comment]
This is part of Apple iOS SDK.
What is your Xcode version?
You should use the latest one.

**Comment by Xiralv** [comment]
@pbakondy thank you for the reply.

My xcode version is 7.0.1(7a1001) 
what is the latest xcode version?
