### ISSUE TITLE
Not recognizing the Words

### ISSUE THREAD

**Issue by martinr77** [pbakondy/cordova-plugin-speechrecognition#48]
I try to show the recognized Words with this code:

```
// Handle results
					function startRecognition(){
						
						window.plugins.speechRecognition.startListening(function(result){
							// Show results in the console
							console.log(result);
						
						}, function(err){
							console.error(err);
						}, {
							language: "de-DE",
							showPopup: true
						});
						
					}
```

It is asking for Permission (so other code is working) and everything is okay, but the only result I get is:

`Ongoing speech recognition`

Why does not he show the words I have spoken? Has it perhaps to do with the matches? Is there an example? How is the right code to show the spoken results into the console.log?

**Comment by chrisworrell** [comment]
Seriously you just close without answering what you might have figured out?

**Comment by desmeit** [comment]
Yes that was the reason. Sorry for that stupid question.

**Comment by gklasen** [comment]
There are people who do not know that on iOS the recognition does not close automatically. Stay professional in terms of answering @chrisworrell.
