### ISSUE TITLE
hide android popup

### ISSUE THREAD

**Issue by muhammadsamir11** [pbakondy/cordova-plugin-speechrecognition#7]
hi i wanna ask you how can i remove android popup same like ios so i can use my own design.

**Comment by pbakondy** [comment]
What popup?

**Comment by muhammadsamir11** [comment]
![screenshot_20161123-145211](https://cloud.githubusercontent.com/assets/1505385/20559151/af346e82-b18c-11e6-9b5a-857eddb36e5d.png)

**Comment by pbakondy** [comment]
ready

**Comment by muhammadsamir11** [comment]
Thanks a lot highly appreciated

**Comment by muhammadsamir11** [comment]
i try the latest updated but i am still getting the android speech popup

**Comment by pbakondy** [comment]
You have to modify the parameters, please check the README

**Comment by jeesoncherukattil** [comment]
make the showPopup: false
