### ISSUE TITLE
Phonegap build

### ISSUE THREAD

**Issue by marcarausch** [pbakondy/cordova-plugin-speechrecognition#8]
I am getting this issue on phonegap for the IOS build:

**_The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-plugin-speechrecognition_**

The android build works.

My config.xml file in my ionic app has this line:
<gap:plugin name="cordova-plugin-speechrecognition" source="npm" />

**Comment by pbakondy** [comment]
I need logs with more detail

**Comment by marcarausch** [comment]
This is the log file fro phonegap: 

[speech plugin log.txt](https://github.com/pbakondy/cordova-plugin-speechrecognition/files/633648/speech.plugin.log.txt)

**Comment by pbakondy** [comment]
This is the key:

```
In file included from /tmp/gimlet/1527634/project/Healthdocs/Plugins/cordova-plugin-speechrecognition/SpeechRecognition.m:5:
/tmp/gimlet/1527634/project/Healthdocs/Plugins/cordova-plugin-speechrecognition/SpeechRecognition.h:2:9: fatal error: 'Speech/Speech.h' file not found
#import <Speech/Speech.h>
        ^
1 error generated.
```

I don't know phonegap environment but try adding `Speech.framework` to the iOS environment.
Cordova build adds it automatically.

See:
https://github.com/pbakondy/cordova-plugin-speechrecognition/blob/master/plugin.xml#L58

**Comment by tobiasmuecksch** [comment]
In my opinion, this issue can be closed

**Comment by pbakondy** [comment]
reason?

**Comment by tobiasmuecksch** [comment]
Inactivity and obliviously no bug of the plugin. You already offered a perfect answer.
