### ISSUE TITLE
Getting 'undefined' is not an object (evaluating 'window.plugins.speechrecognition')

### ISSUE THREAD

**Issue by HemDutt** [pbakondy/cordova-plugin-speechrecognition#83]
I installed this plugin through terminal in my Cordova project directory and it added corresponding folder in my root/plugins directory and platforms/ios/www/plugins directory.

But when I run following code

```
<html>
<p id="demo"></p>
<button type="button" onclick="checkPlugin()">Check Plugin!

<script>

function checkPlugin()
{
  window.plugins.speechRecognition.isRecognitionAvailable(function(available){
    if(available){
        // You can use the speechRecognition
    }
  }, function(err){
      console.error(err);
  });
}
</script>
</html>
```

it crashes after giving error 'undefined' is not an object (evaluating 'window.plugins.speechRecognition')

**Comment by pbakondy** [comment]
you should wait for deviceready event

**Comment by HemDutt** [comment]
Thanks. Worked.
